[package]
name = "hoo_cli"
version = "0.1.0"
authors = ["picklenerd <jordan.t.grace@gmail.com>"]
edition = "2018"

[dependencies]
hoo = { path = "../hoo" }
hoo_api = { path = "../hoo_api" }
dotenv = "0.13.0"
clap = "2.32.0"