[package]
name = "hoo_cli"
version = "0.1.0"
authors = ["jordan"]
edition = "2018"

[[bin]]
name = "hoo"
path = "src/main.rs"

[dependencies]
hoo_api = { path = "../hoo_api" }
anyhow = "1.0"
dotenv = "0.15"
structopt = "0.3"
tokio = { version = "0.2", features = ["macros"] }
