[package]
name = "hoo_api"
version = "0.1.0"
authors = ["picklenerd <jordan.t.grace@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
ron = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"