[package]
name = "hoo_api"
version = "0.1.0"
authors = ["picklenerd <jordan.t.grace@gmail.com>"]
edition = "2018"

[dependencies]
hoo_api_types = { path = "../hoo_api_types" }
anyhow = "1.0"
hyper = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"