[package]
name = "hoo_frontend"
version = "0.1.0"
authors = ["jordan"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
hoo_api_types = { path = "../hoo_api_types" }
seed = "0.5"
wasm-bindgen = "0.2"
