[package]
name = "hoo_server"
version = "0.1.0"
authors = ["picklenerd <jordan.t.grace@gmail.com>"]
edition = "2018"

[dependencies]
hoo_base = { path = "../hoo_base" }
hoo_api = { path = "../hoo_api" }
anyhow = "1.0"
hyper = "0.13"
lazy_static = "1.4"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3.7"
tokio = { version = "0.2", features = ["full"] }
