[package]
name = "hoo_server"
version = "0.1.0"
authors = ["picklenerd <jordan.t.grace@gmail.com>"]
edition = "2018"

[dependencies]
hoo_base = { path = "../hoo_base" }
hoo_api = { path = "../hoo_api" }
actix-web = "1.0"
actix-files = "0.1.2"
clap = "2.33.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.13.0"
failure = "0.1.3"